Repository dnvgl/qats, pull requests merged in 2019-08, with the labels that each got.

#28 TsDB: improved list() method and new get method
  data/simo_r1.key
  data/simo_r1.ts
  data/simo_r2.key
  data/simo_r2.ts
  qats/ts.py
  qats/tsdb.py
  test/test_tsdb.py
Labels: bug, enhancement

#36 Changelog implementation
  CHANGELOG.md
  README.md
Labels: enhancement

#37 sima h5 reader bugfix
  data/h5_examples_RiflexSimpleFlexibleRiser/results_SIMA341.h5
  data/h5_examples_RiflexSimpleFlexibleRiser/results_SIMA35.h5
  data/h5_examples_RiflexSimpleFlexibleRiser/results_SIMA36.h5
  data/h5_examples_RiflexSimpleFlexibleRiser/results_SIMA37dev.h5
  docs/source/conf.py
  qats/readers/sima_h5.py
  qats/ts.py
Labels: bug, enhancement

#39 Moved exceptionhook so that it is activated regardless of how the gui is launched
  qats/cli.py
  setup.py
Labels: bug

#43 Version bumper script to set correct git tag
  version_bumper.py
Labels: enhancement
